# Generated by Django 4.0.4 on 2022-04-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='link',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='name', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
